---
controller_credential_types:
- name: PostgreSQL Database FastAPI
  description: Credential type for PostgreSQL Database FastAPI
  kind: cloud
  inputs:
    fields: []
    required: []
  injectors:
    extra_vars: {}
