---
controller_credentials:
- name: PostgreSQL Database FastAPI - fastapi_tutorial
  description: Credential for fastapi_tutorial
  organization: Default
  credential_type: PostgreSQL Database FastAPI
  update_secrets: true
  inputs: {}
